services:
  app:
    image: node:22.12.0-bookworm
    container_name: MarkdownNode
    working_dir: /app
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    command: sleep infinity
